### ISSUE TITLE
Install Instructions Not Complete

### ISSUE THREAD

**Issue by dhensle** [ActivitySim/sharrow#25]
Following[ install instructions](https://activitysim.github.io/sharrow/intro.html#:~:text=You%20can%20also%20install%20from%20the%20source%20code%20using%20setuptools%20and%20pip.) from the documentation will not pass the [tests](https://activitysim.github.io/sharrow/intro.html#:~:text=run%20pytest%20in%20the%20root%20directory%20of%20the%20sharrow%20repository).  First issue is that openmatrix was not included in the package list.  After installing openmatrix, got another error that says "ValueError: unrecognized engine zarr must be one of: ['scipy', 'store']" in many places. 

Instead of trying to figure out the package issues one-by-one, I just created a new environment using [testing.yml](https://github.com/ActivitySim/sharrow/blob/main/envs/testing.yml) followed by "pip install -e ." in the cloned directory.  The tests then passed successfully.

The installation documentation should be updated to include the extra packages or should just point to an environment file (or both?).

**Comment by dhensle** [comment]
Suggest adding the jupyter related package requirements to the environment yaml as well.

**Comment by jpn--** [comment]
This has been fixed.
